export const searchForm = document.querySelector('.search__form')
export const loadingSection = document.querySelector('.loading')
export const nfoundSection = document.querySelector('.nfound')
export const errorSection = document.querySelector('.error')
export const resultSection = document.querySelector('.result')
export const resultContainer = document.querySelector('.result__container')
export const resultButton = document.querySelector('.result__button')
